### ISSUE TITLE
How about adding Venus as well? 

### ISSUE THREAD

**Issue by petrisch** [mangott/Mars#1]
Should be possible right?

**Comment by mangott** [comment]
Sure ;-) Why don't you collaborate and make a pull request?

**Comment by petrisch** [comment]
But I know nothing about Venus, this is your project, just do it for me please :rofl:

**Comment by mangott** [comment]
Here you go: https://github.com/mangott/Mars/blob/main/solar-system.txt
The whole solar system ;-)
